CREATE TYPE "BookStatus" AS ENUM (
  'available',
  'loaned',
  'maintenance',
  'lost'
);

CREATE TYPE "Condition" AS ENUM (
  'good',
  'average',
  'poor'
);

CREATE TABLE "authors" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ DEFAULT (now()),
  "name" VARCHAR NOT NULL
);

CREATE TABLE books (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    openlibrary_id VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    author_id INTEGER NOT NULL REFERENCES authors(id),
    description TEXT,
    first_publish_year INTEGER,
    editions INTEGER,
    num_pages INTEGER,
    "status" "BookStatus" NOT NULL DEFAULT 'available'
);


CREATE TABLE "genres" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR UNIQUE NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT (now())
);

CREATE TABLE "book_genres" (
  "book_id" INTEGER REFERENCES "books"(id),
  "genre_id" INTEGER REFERENCES "genres"(id),
  PRIMARY KEY ("book_id", "genre_id")
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cpf" CHAR(11) UNIQUE NOT NULL,
  "name" VARCHAR NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT (now())
);

CREATE TABLE book_loans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    book_id INTEGER NOT NULL REFERENCES books(id),
    loan_date TIMESTAMPTZ DEFAULT now(),
    due_date TIMESTAMPTZ,
    returned_at TIMESTAMPTZ
);